"""Adding NLT and NIV tables, for real

Revision ID: 9a4c7d4f9556
Revises: 
Create Date: 2022-11-30 12:58:27.912289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4c7d4f9556'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verses')
    op.drop_table('nlt__verses')
    op.drop_table('niv__verses')
    op.drop_constraint('memorized_verse_id_fkey', 'memorized', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('memorized_verse_id_fkey', 'memorized', 'verses', ['verse_id'], ['id'])
    op.create_table('niv__verses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('verse', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='niv__verses_pkey')
    )
    op.create_table('nlt__verses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('verse', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='nlt__verses_pkey')
    )
    op.create_table('verses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('verse', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='verses_pkey')
    )
    # ### end Alembic commands ###
